use_frameworks!

target 'AutoLayoutExtension_Example' do
  pod 'AutoLayoutExtension', :path => '../'

  target 'AutoLayoutExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
